name: 演習3
# イベントの手動実行
on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
jobs:
  windows-hello:
    runs-on: windows-latest
    steps:
      - name: output
        run: echo "Hello, GitHub Actions."
